project:
  type: book

book:
  chapters:
    - index.qmd
    - template.qmd
  appendices:
    - appendix.qmd

title: My Oxford Thesis
format:
  oxford-thesis-pdf:
    keep-tex: false # set to true to keep the .tex file after compilation (for debugging and final customization)
  oxford-thesis-html: default
author: Your Name
college: Your College
term: Term
year: Year
acknowledgements: |
  Write your acknowledgements section here.
abstract: |
  This document is a template demonstrating the oxford-thesis format. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sit amet nibh volutpat, scelerisque nibh a, vehicula neque. Integer placerat nulla massa, et vestibulum velit dignissim id. Ut eget nisi elementum, consectetur nibh in, condimentum velit. Quisque sodales dui ut tempus mattis. Duis malesuada arcu at ligula egestas egestas. Phasellus interdum odio at sapien fringilla scelerisque. Mauris sagittis eleifend sapien, sit amet laoreet felis mollis quis. Pellentesque dui ante, finibus eget blandit sit amet, tincidunt eu neque. Vivamus rutrum dapibus ligula, ut imperdiet lectus tincidunt ac. Pellentesque ac lorem sed diam egestas lobortis.
keywords: [template, demo]
bibliography: bibliography.bib
